prometheus_web_listen_address: "localhost:9090"
prometheus_web_external_url: "localhost:9090"

prometheus_scrape_configs:
  - job_name: "docker_exporter"
    metrics_path: "/metrics"
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/docker_exporter.yml"

  - job_name: "node_exporter"
    metrics_path: "/metrics"
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/node_exporter.yml"

prometheus_targets:
  docker_exporter:
  - targets:
      - localhost:9323

  node_exporter:
  - targets:
    - localhost:9100


