---

- name: create users
  debug:
    msg: "User {{ item.name }}, Login Shell: {{ item.shell }}"
  loop: "{{ users }}"

- name: create users
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    update_password: always
    state: present
  loop: "{{ users }}"

- name: Add SSH public keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.public_keys }}"
    state: present
  loop: "{{ users }}"

- name: Generate SSH-Keys if they don't exist
  openssh_keypair:
    path: "/home/{{ item.name }}/.ssh/id_ed25519_default"
    type: ed25519
    state: present
    force: false
  loop: "{{ users }}"

- name: Clone the dotfile repository
  git:
    repo: "{{ item.dotfiles }}"
    dest: "/home/{{ item.name }}/.config/dotfiles"
    update: yes
    recursive: yes
  loop: "{{ users }}"

- name: Clone the nvim repository
  git:
    repo: "{{ item.nvim }}"
    dest: "/home/{{ item.name }}/.config/nvim"
    update: yes
  loop: "{{ users }}"

- name: Install oh-my-zsh
  shell: |
    cd "/home/{{ item.name }}/"
    curl -Lo install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    export ZSH=${ZSH:-/home/{{ item.name }}/.oh-my-zsh}
    sh install.sh --unattended
    rm install.sh
  loop: "{{ users }}"

- name: install dotfiles
  shell: |
    cd /home/{{ item.name }}/.config/dotfiles
    HOME=/home/{{ item.name }}/
    sh install.sh
  loop: "{{ users }}"

